### ISSUE TITLE
Persistence workspaces not working

### ISSUE THREAD

**Issue by arnavgr** [mebitek/hyprland#1]
i like your rice and tried using your dots but i couldnt get persistent workspaces to work with waybar.

im using the waybar-hyprland package from aur. can you tell me how you got persistence workspaces to work on hyprland?

**Comment by mebitek** [comment]
Should work as it is. Do you see some errors if you launcher waybar from command line? You can also try ibatalljng waybar-hyprland-git package

**Comment by arnavgr** [comment]
replaced waybar-hyprland with waybar-hyprland-git. still didnt work. the errors i get from running waybar are completely different from what im trying to achieve

```
`[2023-05-01 11:37:20.751] [info] Using configuration file /home/arnav/.config/waybar/config
[2023-05-01 11:37:20.751] [info] Using CSS file /home/arnav/.config/waybar/style.css

(waybar:10101): Gtk-WARNING **: 11:37:20.752: Theme parsing error: style.css:17:11: Not using units is deprecated. Assuming 'px'.
~ ❯❯❯ 
(waybar:10101): Gtk-WARNING **: 11:37:20.818: Theme directory actions/24 of theme Dracula has no size field


(waybar:10101): Gtk-WARNING **: 11:37:20.818: Theme directory actions/32 of theme Dracula has no size field


(waybar:10101): Gtk-WARNING **: 11:37:20.818: Theme directory actions/16@2x of theme Dracula has no size field


(waybar:10101): Gtk-WARNING **: 11:37:20.818: Theme directory actions/22@2x of theme Dracula has no size field


(waybar:10101): Gtk-WARNING **: 11:37:20.818: Theme directory actions/24@2x of theme Dracula has no size field


(waybar:10101): Gtk-WARNING **: 11:37:20.818: Theme directory actions/32@2x of theme Dracula has no size field


(waybar:10101): Gtk-WARNING **: 11:37:20.819: Theme directory actions/symbolic of theme Dracula has no size field


** (waybar:10101): WARNING **: 11:37:20.950: Status Notifier Item with bus name ':1.20' and object path '/org/ayatana/NotificationItem/udiskie' is already registered
ok`
```

**Comment by arnavgr** [comment]
also do i need any other dependencies for your weather script other than python3? i get this error with python3

```
  File "/home/arnav/dotfiles/.config/waybar/bin/./weather.py", line 5, in <module>
    from jproperties import Properties
ModuleNotFoundError: No module named 'jproperties'
```

**Comment by mebitek** [comment]
As I see you need to install Dracula theme.
And yes you need to install some pip dependencies for the weather script. I suggest to run it manually from a command line then run pip install 'module name' (jproperties from the log you sent)

**Comment by mebitek** [comment]
@arnavgr did you edit the waybar config to achieve persistent workspaces? If yes could you please past the relevant part?

**Comment by arnavgr** [comment]
> @arnavgr did you edit the waybar config to achieve persistent workspaces? If yes could you please past the relevant part?

https://github.com/arnavgr/dotfiles/blob/master/.config/waybar/

EDIT: i have commented out the persistent workpaces for now but when i uncomment it, the worspaces are not persistent and remove all glyphs from my other modules

**Comment by mebitek** [comment]
You need to uncomment the persistent part but also the format icons in the workspace configuration

**Comment by arnavgr** [comment]
> You need to uncomment the persistent part but also the format icons in the workspace configuration

i told u uncommenting those lines ruins my entire config. i have done it before it doesnt work. if u want i can send u a picture.

**Comment by mebitek** [comment]
I think u need to install nerd symbols font. However attach picture to me me see

**Comment by arnavgr** [comment]
i use nerd fonts BigBlue_TerminalPlus, is there somewhere i can contact u like reddit or discord, asking on github is a pain

**Comment by mebitek** [comment]
U need nerd font symbols. And yes u can find me in reddit

**Comment by arnavgr** [comment]
closing this here for now will communicate with you on reddit
